In [1]:
import sys
import numpy as np

In [3]:
np.array([12,34,55, 34.5, 67, 45, 1, 5, 23])

array([12. , 34. , 55. , 34.5, 67. , 45. ,  1. ,  5. , 23. ])

In [4]:
list_a = np.array([12 ,34 ,55 , 34.5 , 67 , 45 , 1.0, 5, 23.0], dtype = np.float16)
list_b = np.array([123, 400, 567, 124, 304, 100, 267000], dtype = np.uint32)

print(list_a.dtype)
print(f'{list_a}')

print(list_b.dtype)
print(list_b)
list_a[0], list_a[4]

float16
[12.  34.  55.  34.5 67.  45.   1.   5.  23. ]
uint32
[   123    400    567    124    304    100 267000]


(12.0, 67.0)

In [5]:
# This should extract the third, fifth and the last numbers in the array list
list_b[2], list_b[4], list_b[-1]

(567, 304, 267000)

In [6]:
# Alternatively, you can use multi indexing to achieve the same results
list_b[[0, 4, -2]]


array([123, 304, 100], dtype=uint32)

In [7]:
# Dimensions and shapes
matrix_arr = np.array([
    [12, 4, 56, 90],
    [10, 9, 0, 44]
])

print(matrix_arr)
print(matrix_arr.shape)
print(matrix_arr.ndim)
print(matrix_arr.size)

[[12  4 56 90]
 [10  9  0 44]]
(2, 4)
2
8


## 3-Dimensional Arrays
This is a three-dimensional matrix or a tensor with shape (2, 2, 3), meaning it has 2 matrices, each containing 2 rows and 3 columns.

The first matrix contains the values 1 to 6, and the second matrix contains the values 7 to 12. The elements in the tensor can be accessed using indexing, for example, the element in the first row, second column of the second matrix can be accessed using tensor[1][0][1], which returns the value 8.

```Python
[
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
]
```

In [8]:
three_d_matrix = np.array([
    [
    [13, 7, 9],
    [12, 43, 12]
    ],

    [
    [21, 32, 11],
    [12, 43, 4] 
    ]
])
print(three_d_matrix)
print(three_d_matrix.shape)
print(three_d_matrix.ndim)
print(three_d_matrix.size)

[[[13  7  9]
  [12 43 12]]

 [[21 32 11]
  [12 43  4]]]
(2, 2, 3)
3
12
